USE [WebSchedule]
GO

/****** Object:  Table [dbo].[MeetDay]    Script Date: 7/1/2025 6:22:52 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MeetDay](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MeetDay] [varchar](50) NULL,
 CONSTRAINT [PK_MeetDays] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

