USE [WebSchedule]
GO

/****** Object:  Table [dbo].[MeetType]    Script Date: 7/1/2025 6:23:32 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MeetType](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MeetType] [varchar](50) NULL,
 CONSTRAINT [PK_MeetType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

